### ISSUE TITLE
Agregar espacio entre el texto y boton Imprimir en billing.html

### ISSUE THREAD

**Issue by NavizDev** [Azordev/energy-connect-sv#10]
En el diseño orginal esta asi:
![image](https://user-images.githubusercontent.com/40905751/73982944-40da4f80-4903-11ea-8eb3-c18e31f48250.png)

agregar margin.

**Comment by NavizDev** [comment]
Agrege en el archivo billing.css

![image](https://user-images.githubusercontent.com/40905751/73983458-7e8ba800-4904-11ea-9e50-07626f0ca0ed.png)

**Comment by Israel-Laguan** [comment]
Verificado
