### ISSUE TITLE
Quitar borde al boton Realizar Pago. payment.html

### ISSUE THREAD

**Issue by NavizDev** [Azordev/energy-connect-sv#8]
En el diseño orignal no tiene borde.

![image](https://user-images.githubusercontent.com/40905751/73978007-711cf080-48f9-11ea-9722-8fc41b421240.png)

Se puede soluccionar con css

**Comment by NavizDev** [comment]
en el archivo reset.css agregaron lo siguiente:
![image](https://user-images.githubusercontent.com/40905751/73979794-e0e0aa80-48fc-11ea-894a-49dced1a8405.png)

Tuve que poner !important
![image](https://user-images.githubusercontent.com/40905751/73979833-f3f37a80-48fc-11ea-9fca-adc5abd46229.png)

**Comment by Israel-Laguan** [comment]
Voy a revisar en mi pc y si esta bien cierro la issue

**Comment by Israel-Laguan** [comment]
Verificado: 
![image](https://user-images.githubusercontent.com/36519478/73981170-b2180380-48ff-11ea-99c8-2605efc168ee.png)
